name: Build

on:
  push:
    branches:
      - '*'
      - '!pages'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo --version
        cargo build --all-features --verbose
    - name: Test
      run: cargo test --all-features --verbose
    - name: Clippy
      run: cargo clippy --all-features --verbose -- -D warnings
    - name: Check Format
      run: cargo fmt -- --check

  build-web:
    needs: build-main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Init web
      working-directory: web/
      run: |
        node --version
        yarn --version
        yarn install
    - name: Build
      working-directory: web/
      run: yarn build
